<?php

namespace Checkout;

class OAuthScope
{
    public static $Accounts = "accounts";
    public static $Balances = "balances";
    public static $BalancesView = "balances:view";
    public static $CardManagement = "card-management";
    public static $Disputes = "disputes";
    public static $DisputesAccept = "disputes:accept";
    public static $DisputesProvideEvidence = "disputes:provide-evidence";
    public static $DisputesSchemeFiles = "disputes:scheme-files";
    public static $DisputesView = "disputes:view";
    public static $Files = "files";
    public static $FilesDownload = "files:download";
    public static $FilesRetrieve = "files:retrieve";
    public static $FilesUpload = "files:upload";
    public static $FinancialActions = "financial-actions";
    public static $FinancialActionsView = "financial-actions:view";
    public static $Flow = "flow";
    public static $FlowEvents = "flow:events";
    public static $FlowWorkflows = "flow:workflows";
    public static $Forward = "forward";
    public static $ForwardSecrets = "forward:secrets";
    public static $Fx = "fx";
    public static $Gateway = "gateway";
    public static $GatewayPayment = "gateway:payment";
    public static $GatewayPaymentAuthorization = "gateway:payment-authorizations";
    public static $GatewayPaymentCancellations = "gateway:payment-cancellations";
    public static $GatewayPaymentCaptures = "gateway:payment-captures";
    public static $GatewayPaymentContexts = "gateway:payment-contexts";
    public static $GatewayPaymentDetails = "gateway:payment-details";
    public static $GatewayPaymentRefunds = "gateway:payment-refunds";
    public static $GatewayPaymentVoids = "gateway:payment-voids";
    public static $IssuingCardManagementRead = "issuing:card-management-read";
    public static $IssuingCardManagementWrite = "issuing:card-management-write";
    public static $IssuingCardMgmt = "issuing:card-mgmt";
    public static $IssuingClient = "issuing:client";
    public static $IssuingDisputesRead = "issuing:disputes-read";
    public static $IssuingDisputesWrite = "issuing:disputes-write";
    public static $IssuingControlsRead = "issuing:controls-read";
    public static $IssuingControlsWrite = "issuing:controls-write";
    public static $IssuingTransactionsRead = "issuing:transactions-read";
    public static $IssuingTransactionsWrite = "issuing:transactions-write";
    public static $Marketplace = "marketplace";
    public static $Middleware = "middleware";
    public static $MiddlewareMerchantsPublic = "middleware:merchants-public";
    public static $MiddlewareMerchantsSecret = "middleware:merchants-secret";
    public static $PaymentContext = "Payment Context";
    public static $PaymentSessions = "payment-sessions";
    public static $PaymentsSearch = "payments:search";
    public static $PayoutsBankDetails = "payouts:bank-details";
    public static $Reports = "reports";
    public static $ReportsView = "reports:view";
    public static $SessionsApp = "sessions:app";
    public static $SessionsBrowser = "sessions:browser";
    public static $Transactions = "transactions";
    public static $Transfers = "transfers";
    public static $TransfersCreate = "transfers:create";
    public static $TransfersView = "transfers:view";
    public static $Vault = "vault";
    public static $VaultApmeEnrollment = "vault:apme-enrollment";
    public static $VaultCardMetadata = "vault:card-metadata";
    public static $VaultCustomers = "vault:customers";
    public static $VaultInstruments = "vault:instruments";
    public static $VaultNetworkTokens = "vault:network-tokens";
    public static $VaultRealTimeAccountUpdater = "vault:real-time-account-updater";
    public static $VaultTokenization = "vault:tokenization";
}
