name: build-legacy
on:
    push:
        branches:
            - legacy
jobs:
    build:
        if: "!contains(github.event.commits[0].message, 'Release')"
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 1
            fail-fast: false
            matrix:
                os: [ ubuntu-latest, windows-latest ]
                php-version: [ "5.6" , "7.4" ]
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions: fileinfo
                    coverage: xdebug
            -   name: Installed version
                run: php -v
            -   name: Composer validate
                run: composer validate
            -   name: Composer install
                run: composer install
            -   name: Run PHPUnit
                env:
                    CHECKOUT_SECRET_KEY: ${{ secrets.IT_CHECKOUT_SECRET_KEY }}
                    CHECKOUT_PUBLIC_KEY: ${{ secrets.IT_CHECKOUT_PUBLIC_KEY }}
                run: vendor/bin/phpunit --verbose
